# -*- coding: utf-8 -*-
"""task 1 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gckupU2eyXNI-BnRwwge6JSF6Q4HLqnz
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install python_speech_features
import zipfile
import os
from scipy.io.wavfile import read
import librosa
import matplotlib.pyplot as plt
from python_speech_features import mfcc, logfbank
import numpy as np

directory = '/content/hemant/dataset/Actor_01'

with zipfile.ZipFile('/content/drive/MyDrive/Hemanth/archive.zip', 'r') as zip:
  zip.extractall('/content/hemant/dataset')

sig_rate = []
mfcc_features = []

for filename in os.listdir(directory)[0:5]:
  plt.rcParams["figure.figsize"] = [7.50, 3.50]
  plt.rcParams["figure.autolayout"] = True
  input_data = read(directory+ '/' + filename)
  freq_sampling = input_data[0]
  audio = input_data[1]
  plt.plot(audio[0:1024])
  plt.ylabel("Amplitude")
  plt.xlabel("Time")
  plt.show()


  (sig, rate) = librosa.load(directory+'/'+filename, sr=None)
  sig_rate.append((sig, rate))
  features_mfcc = mfcc(audio, freq_sampling)
  mfcc_features.append(features_mfcc)

sig_rate